; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2.0.4 on Tue Sep 17 2019 17:14:16 GMT-0400 (Eastern Daylight Time)

