; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.0.4 on Tue Sep 17 2019 17:14:16 GMT-0400 (Eastern Daylight Time)
; Wait for set temperatures to be reached
M116 P0

